name: shokher_bari
description: A Global Brand

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  fluttertoast: ^8.0.8
  uuid: ^3.0.5
  carousel_pro_nullsafety: ^1.0.2
  provider: ^6.0.2
  im_stepper: ^0.1.3
  image_picker: ^0.8.4+11

  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  flutterfire_ui: ^0.3.6+1
  firebase_storage: ^10.2.10
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  intl: ^0.17.0
  url_launcher: ^6.1.0

  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins_Extra_Light.ttf
        - asset: assets/fonts/Poppins_Medium.ttf
        - asset: assets/fonts/Poppins_Regular.ttf
          style: normal


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
